apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: female_ghost-backend
  namespace: default
spec:
  maxReplicas: 100
  minReplicas: 1
  scaleTargetRef:
    apiVersion: extensions/v1beta1
    kind: Deployment
    name: default
  targetCPUUtilizationPercentage: 90
