apiVersion: v1
kind: ConfigMap
metadata:
  name: female_ghost-proxy-conf
  namespace: default
data:
  default.conf: |+
    # limit_conn_zone $server_name zone=perserver:10m;
    upstream female_ghost {
        server female_ghost-backend:8000;
        keepalive 100;
    }

    server {
        listen 8000;
        server_name         localhost;

        gzip on;
        gzip_types '*';

        location / {
            # echo 'this text will come in response body with HTTP 200 after 5 seconds';
            keepalive_timeout 100;
            proxy_redirect off;
            proxy_buffering off;
            proxy_pass      http://female_ghost;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $http_x_forwarded_for;
            proxy_set_header X-Forwarded-For $http_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto $http_x_forwarded_proto;
            }

        location /static {
            alias   /usr/src/app/female_ghost/static;
        }

        location /media {
            alias   /usr/src/app/female_ghost/media;
        }
        }


