apiVersion: v1
kind: ConfigMap
metadata:
  name: female_ghost_backend-proxy-conf
  namespace: default
data:
  proxy.conf: |
    map $http_user_agent $is_desktop {
        default 0;
        ~*linux.*android|windows\s+(?:ce|phone) 0; # exceptions to the rule
        ~*spider|crawl|slurp|bot 1; # bots
        ~*windows|linux|os\s+x\s*[\d\._]+|solaris|bsd 1; # OSes
        ApacheBench/2.3 1;
        GoogleHC/1.0 1;
    }

    map $is_desktop $is_mobile {
        1 0;
        0 1;
    }

    map $sent_http_content_type $cache_control {
        default "public,max-age=300";
        text/html no-cache;
        "text/html; charset=utf-8" no-cache;
        "" no-cache; # for 304 Not modified on text/html
    }

    server {
        listen 8000;
        server_name         localhost;
        charset utf-8;

        gzip on;
        gzip_types '*';
        gzip_proxied any;  # to enable gzip in Cloud Load Balancer Proxies

        location / {
            # if ($http_x_forwarded_proto = 'http'){
                # return 302 https://$host$request_uri;
            # }
            add_header Cache-Control $cache_control;  # to allow the CDN to cache our files
            add_header Strict-Transport-Security "max-age=0; includeSubDomains";
            if (-f /usr/share/nginx/html/maintenance.html) {
                return 503;
            }
            index index.html;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            if ($is_mobile) {
                set $version 0;
            }
            if ($is_desktop) {
                set $version 1;
            }
            if ($arg_desktop = 1){
                add_header Set-Cookie desktop=1;
                return 302 $scheme://$host;
            }
            if ($arg_desktop = 0){
                add_header Set-Cookie desktop=0;
                return 302 $scheme://$host;
            }
            if ($cookie_desktop = 0){
                set $version 0;
            }
            if ($cookie_desktop = 1){
                set $version 1;
            }
            if ($version = 0){  # show mobile
                proxy_pass      http://localhost:8000;
                break;
            }
            if ($version = 1){  # show desktop
                proxy_pass      http://localhost:8000;
                break;
            }
          }

          error_page  405     =200 $uri;
          error_page 404 =302 /;
          error_page  497 http://$host$request_uri;
          error_page   503  /maintenance.html;
          location = /maintenance.html {
              root   /usr/share/nginx/html;
          }
      }
