apiVersion: v1
kind: Service
metadata:
  labels:
    run: female_ghost-cloud-endpoint
  name: female_ghost-cloud-endpoint
  namespace: default
spec:
  externalTrafficPolicy: Cluster
  ports:
  - name: http
    port: 8000
    protocol: TCP
    targetPort: 8000
  selector:
    run: female_ghost-cloud-endpoint
  sessionAffinity: None
  type: NodePort
status:
  loadBalancer: {}
