apiVersion: v1
kind: Service
metadata:
  labels:
    Run: female_ghost-proxy
  name: female_ghost-proxy
  namespace: default
spec:
  externalTrafficPolicy: Cluster
  ports:
  - name: http
    port: 8000
    protocol: TCP
    targetPort: 8000
  selector:
    run: female_ghost-proxy
  sessionAffinity: None
  type: NodePort
status:
  loadBalancer: {}